// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZHJ37fcFUxoi_Ih03gsCodX-19zTNgTs',
    appId: '1:1014219256689:web:fbfd6b5f60cd97651ffcd0',
    messagingSenderId: '1014219256689',
    projectId: 'instagramclone-1823e',
    authDomain: 'instagramclone-1823e.firebaseapp.com',
    storageBucket: 'instagramclone-1823e.appspot.com',
    measurementId: 'G-QYXT5VFN8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeOseagilC597CD-G-bEVvbbwamhFn_iU',
    appId: '1:1014219256689:android:3d3569ba7d4a76a31ffcd0',
    messagingSenderId: '1014219256689',
    projectId: 'instagramclone-1823e',
    storageBucket: 'instagramclone-1823e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_pbenAmxCWMRiF59CS8CBPT0Tm3w8NM',
    appId: '1:1014219256689:ios:77a383752044d0691ffcd0',
    messagingSenderId: '1014219256689',
    projectId: 'instagramclone-1823e',
    storageBucket: 'instagramclone-1823e.appspot.com',
    androidClientId: '1014219256689-mq1a3de3tsj8ot9kb2mqkp68atuimf78.apps.googleusercontent.com',
    iosClientId: '1014219256689-01i768f3rkojgo7b2ju3o74q6pm9rq08.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_pbenAmxCWMRiF59CS8CBPT0Tm3w8NM',
    appId: '1:1014219256689:ios:3e26e5b9f351293f1ffcd0',
    messagingSenderId: '1014219256689',
    projectId: 'instagramclone-1823e',
    storageBucket: 'instagramclone-1823e.appspot.com',
    androidClientId: '1014219256689-mq1a3de3tsj8ot9kb2mqkp68atuimf78.apps.googleusercontent.com',
    iosClientId: '1014219256689-26hjq2pm2ak0rkq4vgqoeicdf4amkbjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
